[build]
builder = "DOCKER"

[deploy]
numReplicas = 2
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = "3000"
PYTHON_VERSION = "3.11"
NODE_VERSION = "18"
RAILWAY_STATIC_URL = "https://${RAILWAY_STATIC_URL}"
RAILWAY_PUBLIC_DOMAIN = "https://${RAILWAY_PUBLIC_DOMAIN}"

[[services]]
name = "backend"
buildCommand = "pip install -r requirements.txt"
startCommand = "gunicorn api.server:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
autoDeploy = true
healthcheckPath = "/api/health"
healthcheckTimeout = 30

[[services]]
name = "frontend"
buildCommand = "npm install && npm run build"
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT"
autoDeploy = true
healthcheckPath = "/"
healthcheckTimeout = 30

[services.backend.env]
PYTHON_ENV = "production"
LOG_LEVEL = "info"
MAX_WORKERS = "4"

[services.frontend.env]
NODE_ENV = "production"
VITE_API_URL = "${RAILWAY_STATIC_URL}"