[build]
builder = "DOCKER"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = "80"
PYTHONUNBUFFERED = "1"
STORAGE_PATH = "/app/data/biometric_faces"
VITE_API_URL = "https://${RAILWAY_STATIC_URL}/api"