name: deploy-removed

on:
  workflow_dispatch: {}

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder - no operation
        run: |
          echo "This workflow is intentionally disabled. Deployment is handled by ci-cd.yml"